//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlteraBarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class StylesView
    {
        public int Id { get; set; }
        public string Style { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
